package proyectofinal;

import java.sql.CallableStatement;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jibarra
 */
public class insertarFactura extends javax.swing.JPanel {

    /**
     * Creates new form insertarArticulo
     */
    public insertarFactura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        empleadoTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        usuarioTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nombreUsuarioTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        insertarProducto = new javax.swing.JButton();
        codigoEmbarqueTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cantidadTxt = new javax.swing.JTextField();
        provedorTxt = new javax.swing.JTextField();
        modalidadTxt = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        detalleFactura = new javax.swing.JTable();

        jLabel2.setText("Codigo embarque:");

        jLabel3.setText("Proveedor");

        jLabel5.setText("empleado:");

        jLabel6.setText("Modalidad");

        nombreUsuarioTxt.setToolTipText("");

        jLabel7.setText("usuario");

        jLabel8.setText("nombre usuario");

        insertarProducto.setText("Insertar factura");
        insertarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarProductoActionPerformed(evt);
            }
        });

        codigoEmbarqueTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoEmbarqueTxtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("INSERTAR FACTURA");

        jLabel9.setText("cantidad piezas");

        modalidadTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AEREO", "MARÍTIMO", "TERRESTRE" }));
        modalidadTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modalidadTxtActionPerformed(evt);
            }
        });

        detalleFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Articulo", "precio", "cantidad", "total linea"
            }
        ));
        jScrollPane1.setViewportView(detalleFactura);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(empleadoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(codigoEmbarqueTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(provedorTxt))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(usuarioTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nombreUsuarioTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(modalidadTxt, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cantidadTxt)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(insertarProducto)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(codigoEmbarqueTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(modalidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(usuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(provedorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nombreUsuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(empleadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cantidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(insertarProducto)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void insertarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarProductoActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(this.codigoEmbarqueTxt.getText());
        int proveedor = Integer.parseInt(this.provedorTxt.getText());
        int empleado = Integer.parseInt(this.empleadoTxt.getText());
        String modalidad = this.modalidadTxt.getSelectedItem().toString();
        int usuario = Integer.parseInt(this.usuarioTxt.getText());
        String nombreUsuario = this.nombreUsuarioTxt.getText();
        int cantidad = Integer.parseInt(this.cantidadTxt.getText());
        ResultSet rs = null;
        SimpleDateFormat formatoDelTexto = new SimpleDateFormat("yyyy-MM-dd");
        Date fecha = new Date(116, 5, 3);

        try {
            Statement sql = conexion.getConexion().createStatement();
            CallableStatement cst = conexion.getConexion().prepareCall("{call FACTURACION_E (?,?,?,?,?,?,?,?,?,?)}");
            cst.setInt("CODIGO_EMBARQUE", codigo);
            cst.setInt("PROVEEDOR", proveedor);
            cst.setDate("FECHA_INGRESO", fecha);
            cst.setInt("EMPLEADO_RECIBE", empleado);
            cst.setString("MODALIDAD_EMBARQUE", modalidad);
            cst.setInt("USUARIO", usuario);
            cst.setString("NOMBRE_USUARIO", nombreUsuario);
            cst.setInt("CANTIDAD_PIEZAS", cantidad);

            cst.registerOutParameter("RESULT", java.sql.Types.VARCHAR);
            cst.registerOutParameter("RESULT1", java.sql.Types.VARCHAR);
            //cst.registerOutParameter("CONTRASEÑA", java.sql.Types.VARCHAR);

            cst.execute();
            String respuesta = cst.getString(9);
            JOptionPane.showMessageDialog(null, respuesta);
            int numeroLinea;
            int articulo;
            double precio;
            double cantidadD;
            int totalLinea;
            for (int i = 0; i < detalleFactura.getRowCount(); i++) {
                CallableStatement cst2;
                cst2 = conexion.getConexion().prepareCall("{call FACTURACION_D (?,?,?,?,?,?,?,?)}");
                cst2.setInt("CODIGO_EMBARQUE", codigo);
                numeroLinea = i+1;
                cst2.setInt("NUMERO_LINEA", numeroLinea);
                articulo = Integer.parseInt(detalleFactura.getValueAt(i, 1).toString());
                cst2.setInt("ARTICULO", articulo);
                precio = Double.parseDouble(detalleFactura.getValueAt(i, 2).toString());
                cst2.setDouble("PRECIO", precio);
                cantidadD = Double.parseDouble(detalleFactura.getValueAt(i, 3).toString());
                cst2.setDouble("CANTIDAD", cantidadD);
                totalLinea = Integer.parseInt(detalleFactura.getValueAt(i, 3).toString());
                cst2.setInt("TOTAL_LINEA", totalLinea);
                cst2.registerOutParameter("RESULT", java.sql.Types.VARCHAR);
                cst2.registerOutParameter("RESULT1", java.sql.Types.VARCHAR);
                cst2.execute();
                String respuesta2 = cst2.getString(8);
                JOptionPane.showMessageDialog(null, respuesta2);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }


    }//GEN-LAST:event_insertarProductoActionPerformed

    private void codigoEmbarqueTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoEmbarqueTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoEmbarqueTxtActionPerformed

    private void modalidadTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modalidadTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modalidadTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidadTxt;
    private javax.swing.JTextField codigoEmbarqueTxt;
    private javax.swing.JTable detalleFactura;
    private javax.swing.JTextField empleadoTxt;
    private javax.swing.JButton insertarProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> modalidadTxt;
    private javax.swing.JTextField nombreUsuarioTxt;
    private javax.swing.JTextField provedorTxt;
    private javax.swing.JTextField usuarioTxt;
    // End of variables declaration//GEN-END:variables
}
