/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jibarra
 */
public class listaArticulos extends javax.swing.JPanel {

    /**
     * Creates new form listaArticulos
     */
    public listaArticulos() {
        initComponents();
        ResultSet rs = null;
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("Tipo");
        modelo.addColumn("Precio");
        modelo.addColumn("Pais");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Estado");
        modelo.addColumn("Nombre");
        modelo.addColumn("Fabricante");
        String SQL = "SELECT st.CODIGO, st.TIPO_ARTICULO,st.PRECIO_VENTA,st.PAIS_ORIGEN,CANTIDAD_STOCK,st.ESTADO,st.NOMBRE,fb.NOMBRE as fabri FROM STOCK st inner join FABRICANTE fb on fb.CODIGO = st.FABRICANTE";
        try {
            Statement sql = conexion.getConexion().createStatement();
            rs = sql.executeQuery(SQL);
              while (rs.next()) {
                //System.out.println(rs.getString("columna") + ", " + rs.getString("columna"));
                modelo.addRow(new Object[]{rs.getInt("CODIGO"),rs.getString("TIPO_ARTICULO"),rs.getInt("PRECIO_VENTA")
                ,rs.getInt("PAIS_ORIGEN"), rs.getInt("CANTIDAD_STOCK"),rs.getString("ESTADO"),rs.getString("NOMBRE"),
                rs.getString("fabri")});
             }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        this.stockList.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        stockList = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        stockList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Tipo", "Precio", "Pais", "Cantidad", "Estado", "Nombre", "Fabricante"
            }
        ));
        jScrollPane1.setViewportView(stockList);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Lista productos en STOCK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable stockList;
    // End of variables declaration//GEN-END:variables
}
